"""State schema for individual research agent.

This module defines the state used by individual research agents (Level 3).
Each research agent has an isolated context with no awareness of the parent
research or other parallel agents.
"""

from typing_extensions import TypedDict, Annotated, Sequence
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field
import operator


class ResearcherState(TypedDict):
    """State for individual research agent (Level 3).
    
    ISOLATED CONTEXT: This agent has NO awareness of:
    - Parent research_topic or research_scope
    - Other parallel sub-agents  
    - Why this research is being conducted
    
    It ONLY knows what the supervisor tells it:
    - research_subtopic: Specific focus area assigned by supervisor
    - research_questions: List of questions to answer (generated by supervisor)
    """
    
    # Private message history (ISOLATED from supervisor and other agents)
    researcher_messages: Annotated[Sequence[BaseMessage], add_messages]
    
    # Supervisor-provided: Specific subtopic for THIS agent
    # Example: "OpenAI Deep Research product features and capabilities"
    research_subtopic: str
    
    # Supervisor-provided: List of specific questions to answer
    # Example: ["What are the key features?", "How does pricing work?", "What are user reviews?"]
    research_questions: list[str]
    
    # Final output: Compressed research findings
    compressed_research: str
    
    # Raw search results (for debugging/traceability)
    raw_notes: Annotated[list[str], operator.add]


class Summary(BaseModel):
    """Schema for webpage content summarization.
    
    Used for structured output when summarizing raw webpage content.
    """
    summary: str = Field(description="Concise summary of the webpage content")
    key_excerpts: str = Field(description="Important quotes and excerpts from the content")

