from typing_extensions import Annotated
from langgraph.graph import MessagesState
import operator

# ===== STATE FOR THE MAIN GRAPH =====

class FullResearchState(MessagesState):
    
    # Research topic and the scope are generated by the advisor through user interaction
    research_topic: str = ""
    research_scope: str = ""
    
    # User approval determines whether to continue advising or start the research supervisor
    user_approved: bool = False
    
    # Notes and raw notes are generated will be generated by supervisor
    notes: Annotated[list[str], operator.add] = []
    raw_notes: Annotated[list[str], operator.add] = []
    
    # Final report is generated by the writer
    final_report: str = ""